//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hydra.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\mzxml\\file07 - run1 - apo-CaM 50%0025D2O trial1.wiff.mzXML")]
        public string mzXMLTestFile1 {
            get {
                return ((string)(this["mzXMLTestFile1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\mzxml\\file25 - 20l apo trial1-s1 (MSMS).mzXML")]
        public string mzXMLTestFile2 {
            get {
                return ((string)(this["mzXMLTestFile2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\testProjects\\TestProject1\\testProject1.mssproj")]
        public string TestProject1 {
            get {
                return ((string)(this["TestProject1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\peptide_csv\\Peptides7-13.csv")]
        public string PeptideTestFile1 {
            get {
                return ((string)(this["PeptideTestFile1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\mzxml")]
        public string TestRunDataDirectory {
            get {
                return ((string)(this["TestRunDataDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\testProjects\\TestProject2\\testProject2.mssproj")]
        public string TestProject2 {
            get {
                return ((string)(this["TestProject2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\testProjects\\TestProject2\\testExperiment2\\Data\\Peptides.xml")]
        public string PeptideTestFile2 {
            get {
                return ((string)(this["PeptideTestFile2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\testProjects\\TestProject1\\testExperiment1\\testExperiment1.mssexp" +
            "")]
        public string TestExperiment1 {
            get {
                return ((string)(this["TestExperiment1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\testProjects\\TestProject1\\TestExperiment1\\Data\\peptides.xml")]
        public string XmlPeptideTestFile {
            get {
                return ((string)(this["XmlPeptideTestFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Results - 2011-02-10 05.46.05.xml")]
        public string ResultFile1 {
            get {
                return ((string)(this["ResultFile1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\testProjects")]
        public string ProjectRootDirectory {
            get {
                return ((string)(this["ProjectRootDirectory"]));
            }
        }
    }
}
