using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: AssemblyProductAttribute("Mass Spec Studio")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Schriemer Lab 2011.")]
[assembly: AssemblyCompanyAttribute("Schriemer Lab")]
[assembly: AssemblyTrademarkAttribute("")]

